---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://translusion.github.com"
title: "Translusion"
date: "26 April 2014"
description: "Erik Engheim's Projects and Articles"
...
